### PR TITLE
Schema function additions

### PR DESCRIPTION
**Pull request by schloerke**
To keep in the spirit of libgraphqlparser (speed), I added a second function `schema2json(txt)` that allows for both queries and schema definitions while still keeping the original 'query only' function `graphql2json(txt)`.   ([link](https://github.com/ropensci/graphql/compare/master...schloerke:schema?expand=1#diff-b2629d2db1956feb32ad4e7040d24dbcR32)) My opinion is to only use the schema and query parsing function, but I see the point of a small speed increase for query only parsing.

Feel free to change the name to something else. :-), just exposing the required functionality.  

I also upgraded the tests for kitchen sink queries and schema definitions.  

Side note...
This update is so nice for me! It saves me about a >1000 lines of code for a small to midsize schema definition.  I will now be able to do something similar to https://github.com/matthewmueller/graph.ql

### CODE REVIEW

**Comment by jeroen** [comment]
Thanks! Perhaps we can avoid duplicating a lot of C code binding code by creating a single c++ function with a parameter that specifies which parser to use? 

```cpp
// [[Rcpp::export]]
Rcpp::String dump_json_ast(Rcpp::String graph, bool schema) {
  graph.set_encoding(CE_UTF8);
  const char *error;
  auto AST = schema ? 
    facebook::graphql::parseStringWithExperimentalSchemaSupport(graph.get_cstring(), &error) :
    facebook::graphql::parseString(graph.get_cstring(), &error);
  if (!AST) {
    char buf[1000];
    strncpy(buf, error, 1000);
    free((void*) error);
    throw std::runtime_error(buf);
  }
  const char *json = graphql_ast_to_json((const struct GraphQLAstNode *)AST.get());
  Rcpp::String out(json);
  out.set_encoding(CE_UTF8);
  free((void*) json);
  return out;
}

```

Would that make sense?

**Comment by schloerke** [comment]
Sounds great to me! Plus it's much less confusing

From the "speed" of R standpoint, I would enable schema parsing by default.

**Comment by schloerke** [comment]
Oops, I made a bad example. Forgot to use the new function... but that'll get fixed with the merging of the functionality

**Comment by schloerke** [comment]
Merged into one function now.  Tests updated.  Added schema example to `graphql2json()` fn.

**Comment by jeroen** [comment]
OK looks good. Can you add yourself as a contributor to `DESCRIPTION`? Also would you mind rebasing to squash the commits into a single commit?

**Comment by schloerke** [comment]
squashed in #7

**Comment by jeroen** [comment]
Thanks. Next time you don't have to do a new PR, just `git push -f` :)

**Comment by schloerke** [comment]
Ah! I've usually just done with within the Github PR (but can't cuz I'm not owner here), didn't know how to do it command line side.  Thank you!

**Comment by jeroen** [comment]
I always have to look it up but it's really easy: https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by jeroen** [comment]
This is on CRAN now.

**Pull request closed without merging**
